name: pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - torchaudio
  - torchvision
  - pytorch
  - cudatoolkit=11.0
  - ipykernel
  - tqdm
  - matplotlib
  - h5py
  - imageio
  - simpleitk
